export const SET_ACTIVE_LANGUAGE = 'SET_ACTIVE_LANGUAGE';

export const SET_WALLET_DATA = 'SET_WALLET_DATA';

export const SET_AUTH_DATA = 'SET_AUTH_DATA';

export const SET_APP_SETTINGS_DATA = 'SET_APP_SETTINGS_DATA';

export const SET_TRANSACTION_DATA = 'SET_TRANSACTION_DATA';

export const STORE_REGISTRATION_FORM_DATA = 'STORE_REGISTRATION_FORM_DATA';

export const CLEAR_REGISTRATION_FORM_DATA = 'CLEAR_REGISTRATION_FORM_DATA';

export const LOCK_APP = 'LOCK_APP';
export const UNLOCK_APP = 'UNLOCK_APP';
export const SET_RAHAT_PASSCODE = 'SET_RAHAT_PASSCODE';
export const UPDATE_BACKINGUP_TO_DRIVE_STATUS = 'UPDATE_BACKINGUP_TO_DRIVE_STATUS';